org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
loader_version_range=[4,)
neo_version=26.1.2.80
ae2_version=26.1.10-beta

## Mod Properties
mod_id=ae2craftcore
mod_name=AE2 CraftCore
mod_license=LGPL-3.0-or-later
mod_version=1.2.0
mod_group_id=org.ae2craftcore
mod_authors=dertex909
mod_description=Auto-crafting addon for Applied Energistics 2 without patterns.